debug: false

caching:
  spring:
    userListTTL: 60000

jwt:
  # inlaco.JWT-secret-key
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 300000 # 5 mins
  refresh-token-expiration: 2592000000 # 30 days

spring:
  application:
    name: "crewmgrservice"
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    transport:
      protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # cache:
  #   type: caffeine
  #   caffeine:
  #     spec: maximumSize=100000,expireAfterAccess=3600s
  #   cache-names:
  #     - rate-limit-buckets
  #     - rate-limit-filter
  #   jcache:
  #     provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER:admin}:${MONGO_PASSWORD}@${MONGO_DATABASE:comic-db}.mmm13.mongodb.net/?retryWrites=true&w=majority&appName=${MONGO_DATABASE:comic-db}
      database: ${MONGO_DATABASE:comic-db}
      autoIndexCreation: true
    # redis:
    #   host: ${REDIS_HOST}
    #   port: ${REDIS_PORT}
    #   password: ${REDIS_PASSWORD:IxXNUvoIE4ZywfZ8PMZ0nmVxVzKwUeC3}
    #

comic:
# cloudinary:
#   cloud_name: ${CLOUDINARY_CLOUD_NAME:foodey}
#   api_key: ${CLOUDINARY_API_KEY}
#   api_secret: ${CLOUDINARY_API_SECRET}
